# Generated by Django 4.0.2 on 2022-02-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Школьная программа',
                'verbose_name_plural': 'Школьные программы',
            },
        ),
        migrations.CreateModel(
            name='Subject_school_curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('school_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school_curriculum', verbose_name='Школьная программа')),
            ],
            options={
                'verbose_name': 'Предмет школьной программы',
                'verbose_name_plural': 'Предмет школьной программы',
            },
        ),
    ]
