# Generated by Django 3.2.5 on 2021-11-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'db_table': 'Школьная программа',
            },
        ),
        migrations.CreateModel(
            name='Subject_school_curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('school_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school_curriculum')),
            ],
            options={
                'db_table': 'Предмет школьной программы',
            },
        ),
    ]
