# Generated by Django 3.2.5 on 2021-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_curriculum',
            options={'verbose_name': 'Школьная программа', 'verbose_name_plural': 'Школьная программа'},
        ),
        migrations.AlterModelOptions(
            name='subject_school_curriculum',
            options={'verbose_name': 'Предмет школьной программы', 'verbose_name_plural': 'Предмет школьной программы'},
        ),
        migrations.AlterField(
            model_name='school_curriculum',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subject_school_curriculum',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterModelTable(
            name='school_curriculum',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject_school_curriculum',
            table=None,
        ),
    ]
