# Generated by Django 4.0.2 on 2022-02-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_school_curriculum',
            options={'verbose_name': 'Предмет школьной программы', 'verbose_name_plural': 'Предметы школьной программы'},
        ),
    ]
