# Generated by Django 3.2.5 on 2021-11-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211110_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_curriculum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject_school_curriculum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject_school_curriculum',
            name='school_curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school_curriculum', verbose_name='Школьная программа'),
        ),
    ]
