# Generated by Django 4.0.2 on 2022-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subject_school_curriculum_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_school_curriculum',
            name='school_class',
            field=models.CharField(blank=True, choices=[('10 class', '10 класс'), ('11 class', '11 класс')], max_length=50),
        ),
    ]
