# Generated by Django 3.2.5 on 2021-12-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211112_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_curriculum',
            options={'verbose_name': 'Школьная программа', 'verbose_name_plural': 'Школьные программы'},
        ),
    ]
