# Generated by Django 4.0.2 on 2022-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_school_curriculum_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_school_curriculum',
            name='school_class',
            field=models.CharField(blank=True, choices=[('10', '10 класс'), ('11', '11 класс')], max_length=50, verbose_name='Номер класса'),
        ),
    ]
