# Generated by Django 4.0.2 on 2022-03-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subject_school_curriculum_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme_school_subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('subject_school_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject_school_curriculum', verbose_name='Предмет школьной программы программа')),
            ],
            options={
                'verbose_name': 'Тема школьной программы',
                'verbose_name_plural': 'Темы школьных программ',
            },
        ),
    ]
