# Generated by Django 4.0.2 on 2022-03-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_theme_school_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_curriculum',
            new_name='SchoolCurriculum',
        ),
        migrations.RenameModel(
            old_name='Subject_school_curriculum',
            new_name='SubjectSchoolCurriculum',
        ),
        migrations.RenameModel(
            old_name='Theme_school_subjects',
            new_name='ThemeSchoolSubjects',
        ),
    ]
